version: '3.7'

services:
  go-app:
    # build: .
    image: europe-central2-docker.pkg.dev/gleaming-scene-429317-d6/ebiznes-registry/4-go-app
    ports:
      - "1323:1323"
    networks:
      - mynet
    env_file:
      - .env

  react-app:
    # build: ../5-react/my-app/Dockerfile
    image: europe-central2-docker.pkg.dev/gleaming-scene-429317-d6/ebiznes-registry/4-react-app
    ports:
      - "1423:80" 
    stdin_open: true
    tty: true
    depends_on:
      - go-app
    networks:
      - mynet

  tea-shop-db:
    build:
      context: .
      dockerfile: Dockerfile.database
    image: europe-central2-docker.pkg.dev/gleaming-scene-429317-d6/ebiznes-registry/4-go-db-app
    ports:
        - 1433:1433
    networks:
      - mynet
    volumes:
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh
      - ./run-initialization.sh:/usr/src/app/run-initialization.sh
      - ./create_mssql.sql:/usr/src/app/create_mssql.sql
      - ./init_mssql.sql:/usr/src/app/init_mssql.sql

networks:
  mynet:
    driver: bridge
