version: '3.7'

services:
  db:
    build: 
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - /home/pkuszneruk/university/e-biznes/4-go/create.sql:/docker-entrypoint-initdb.d/create.sql
      - /home/pkuszneruk/university/e-biznes/4-go/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet

  go-app:
    build:
      context: .
    ports:
      - "1323:1323"
    depends_on:
      - db
    networks:
      - mynet

  react-app:
    build: ../5-react/my-app
    ports:
      - "3000:80" 
    stdin_open: true
    tty: true
    depends_on:
      - go-app
    networks:
      - mynet

volumes:
  mysql-data:

networks:
  mynet:
    driver: bridge