version: '3.7'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynet

  go-app:
    build:
      context: .
    ports:
      - "1323:1323"
    depends_on:
      - db
    networks:
      - mynet

  react-app:
    build: ../5-react/my-app
    ports:
      - "3000:80" 
    stdin_open: true
    tty: true
    depends_on:
      - go-app
    networks:
      - mynet

volumes:
  mysql-data:

networks:
  mynet:
    driver: bridge